### PR TITLE
Update to 0.0.9

### PR DESCRIPTION
**Pull request by Lonsfor**

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
Failed: https://flathub.org/builds/#/builders/2/builds/1268

`com.github.quaternion:             AppData problem: attribute-missing : <release> has no timestamp`

**Comment by KitsuneRal** [comment]
That's a good catch, I have to make it a habit to update AppData with releases, too.

**Comment by KitsuneRal** [comment]
@Lonsfor, please jump straight to 0.0.9.1, I have fixed some other blunders and also updated to the fresher library with some other fixes.

**Comment by TingPing** [comment]
@KitsuneRal Just add a call to `appstream-util validate` (or `validate-relax`) to the build systems tests.

**Comment by KitsuneRal** [comment]
Thanks, will do.

**Comment by KitsuneRal** [comment]
No more up to date, superseded by #8.

**Pull request closed without merging**
