### PR TITLE
update to 0.0.5

### PR DESCRIPTION
**Pull request by Lonsfor**

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
Hmm failed to build on arm:

```
Renaming com.github.quaternion.appdata.xml to share/appdata/com.github.quaternion.appdata.xml
Error: Target file exists
```

Maybe a bug on the builder not in the package though.

**Comment by TingPing** [comment]
Ah as of this commit https://github.com/QMatrixClient/Quaternion/commit/c274c4595c352b3fb72889044011fbfcbcef83a2 we should remove our appdata file. (Though upstreams file isn't very good either, somebody should improve that)

**Comment by KitsuneRal** [comment]
@TingPing, The work on the appdata file is still ongoing. Thanks for nudging anyway :)

**Comment by KitsuneRal** [comment]
@Lonsfor, would you delete the appdata file within this PR, please?

**Comment by Lonsfor** [comment]
I think that should be it

**Comment by TingPing** [comment]
bot, build

**Pull request merged**
